name: "Deploy to Neltify"
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build
    - run: cp -rL result build
    - run: ls
    - uses: wei/wget@v1
      with:
        args: -O slides.tar.gz "https://github.com/davidnuon/nix-camp-2023/archive/refs/heads/main.tar.gz"
    - run: chmod -R 777 build
    - run: cp slides.tar.gz build
    - name: Deploy Netlify
      uses: danakim/gh-action-deploy-netlify@master
      with:
        AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        DEPLOY_PROD: true