name: "Deploy to Neltify"
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build
    - run: cp -r results out
    - uses: wei/wget@v1
      with:
        args: -O ./out/slides.tar.gz "https://github.com/davidnuon/nix-camp-2023/archive/refs/heads/main.tar.gz"